http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

## Path Settings
path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

## Pipeline Settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

## Monitoring
monitoring.enabled: true
